### ISSUE TITLE
ImportError: No module named jsonpath_rw

### ISSUE THREAD

**Issue by chapayevdauren** [scrapy/scrapyd-client#40]
```File /home/steppe/virtualenvs/the-steppe/local/lib/python2.7/site packages/dynamic_scraper/spiders/django_checker.py, line 3, in <module>  from jsonpath_rw import jsonpath, parse```

**Comment by Digenis** [comment]
Hi, @chapayevdauren 

The scrapyd-client issue tracker is meant for scrapyd-client bugs and features.
It seems that the problem is caused by missing packages
which are required by some of your spiders, not scrapyd-client or any of its dependencies.
For support questions, try the [mailing list](https://groups.google.com/forum/#!forum/scrapy-users)
