### ISSUE TITLE
Could not recognize spiders

### ISSUE THREAD

**Issue by smartfin** [scrapy/scrapyd-client#41]
Hi.
I'm trying to deploy my project to scrapyd-service. 

When I'm deploing to local api everything is Ok. But for remote - I've got 0 spiders. But project still successfully created.

> scrapyd-deploy production --debug
> Packing version 1.5.1
> Deploying to project  in http://x.x.x.x:6800/addversion.json
> Server response (200):
> {"status": "ok", "project": "projectname", "version": "1.5.1", "spiders": 0, "node_name": "ubuntu"}
> 
> Output dir not removed: /tmp/scrapydeploy-DQkIo7
> vagrant@vagrant-ubuntu-trusty-64:/vagrant/parser$ scrapyd-deploy localapi --debug
> Packing version 1.5.1
> Deploying to project "projectname" in http://localhost:6800/addversion.json
> Server response (200):
> {"status": "ok", "project": "projectname", "version": "1.5.1", "spiders": 3, "node_name": "vagrant-ubuntu-trusty-64"}

**Comment by Digenis** [comment]
Hi @smartfin,
are you using scrapy-1.3 in "production" and scrapy-1.2 in "localapi"
See this recently discovered issue with scrapy list:
https://groups.google.com/d/msg/scrapy-users/JlfoQ5LlAl4/8hoXav78BAAJ
It's was fixed in https://github.com/scrapy/scrapy/pull/2632

If downgrading to scrapy-1.2 in "production"
results in exceptions messages being returned from scrapyd,
or whole tracebacks in case of scrapyd-1.2 (currently in alpha)
then it's the above issue.
You'll have to use scrapy-1.2 and wait for scrapy-1.3.3.

**Comment by Digenis** [comment]
@smartfin, scrapy-1.3.3 was just released.

**Comment by redapple** [comment]
@smartfin , have you been able to test with Scrapy 1.3.3?

**Comment by jpmckinney** [comment]
Closing as no response to question.
