### ISSUE TITLE
cannot deploy spiders (0 spiders)

### ISSUE THREAD

**Issue by vc-utelly** [scrapy/scrapyd-client#43]
Hi !

On deploy spiders I am getting this response back:

{"status": "ok", "project": "project_name", "version": "1491906309", "spiders": 0, "node_name": "IP"}

I have 20 spiders local and production are running Scrapy 1.3.3, I installed all dependencies on the production environment 

How can I understand further what is happening?

**Comment by Digenis** [comment]
@vinczente, can you share your project settings here?
(excluding of course any sensitive information)

**Comment by visjedi** [comment]
I have exacty the same issue. Here is my settings file
```
BOT_NAME = 'scrapeurls'

SPIDER_MODULES = ['scrapeurls.spiders']

NEWSPIDER_MODULE = 'scrapeurls.spiders'


# Crawl responsibly by identifying yourself (and your website) on the user-agent
USER_AGENT = 'scrapeurls (http://meow.github.io)'

# Obey robots.txt rules
ROBOTSTXT_OBEY = False


# Configure a delay for requests for the same website (default: 0)
# See http://scrapy.readthedocs.org/en/latest/topics/settings.html#download-delay
# See also autothrottle settings and docs
DOWNLOAD_DELAY = 5


# Disable cookies (enabled by default)
COOKIES_ENABLED = False

# because on one of the stackoverflow answers setting this to true caused spiders:0 to be returned by scrapyd
LOG_STDOUT=False

**Comment by visjedi** [comment]
@vinczente Please check if you have import statements inside your spider scripts which fail when calling `$scrapy list`. This command should list your spiders automatically. In my case, this command failed. In one of the spiders, I imported a function from utils.py (which is in the same folder as the spiders) as follows: `from utils import pick_names`.
To make this work, I had to change the above line to
`from scrapeurls.spiders.utils import pick_names # scrapeurls is the name of my scrapy project`

**Comment by vinczente** [comment]
@visjedi Thanks for the help
scrapy list works and I even can deploy to scrappinghub..

Missing dependencies happen easily, if scrapyd is not able to tell what error it is having, I wont use it.

**Comment by redapple** [comment]
> Missing dependencies happen easily, if scrapyd is not able to tell what error it is having, I wont use it.

@vinczente , it's surely is a bug, somewhere. The thing is that we need help identifying the root cause.
Instead of not using scrapyd, we (the community, you, me etc.) should try to have a reproducible issue, and fix the bug for everyone.

Can you tell us more on your local and production systems? Python version, scrapyd version, platform/OS (Win, Linux, macOS etc.), using virtualenv etc.
(Note: I haven't tried to reproduce it yet myself)

**Comment by IgorAntun** [comment]
I had the exact same issue, and after tweaking with all the possible files and configurations, it turned out to be the `LOG_STDOUT: True` setting. As soon as I set it to `False` (the default), scrapyd deployed the spiders properly.
Unfortunately I'm not sure why this setting leads to this condition, and don't have the time right now to investigate. Perhaps @redapple has an idea why?

ps. just noticed @visjedi had pointed this out in his answer but I didn't see. fml.

**Comment by Digenis** [comment]
@IgorAntun, the LOG_STDOUT setting is a different issue,
at lease according to  @visjedi (we don't know @vinczente's configuration)
there's a ticket about it in scrapy: https://github.com/scrapy/scrapy/pull/2450---

---

@vinczente,

Can you confirm that you don't use `LOG_STDOUT = True`?

Missing dependencies should raise exceptions in the `scrapy list` command
which scrapyd uses. scrapyd won't silence any errors in scrapy-list.
(unless you conditionally define spiders, depending on whether a module is available or not)

Can you share some more information on your project?
It would be useful to know the contents of the settings file/files
(excluding any sensitive information),
the scrapy config `scrapy.cfg`, the packaging script `setup.py`
and the project's directory tree (eg using the tree command)

**Comment by pablosr11** [comment]
Hello team,

Same issue here. When setting `LOG_STDOUT = True`, `scrapy list` doesn't pick up the spiders nor does the `scrapyd`server.

@Digenis  `scrapy list` runs for me with no issues regarding settings. It simply doesn't list the spider when the LOG STDOUT is on. Will try to have a look at it this week -

**Comment by Digenis** [comment]
`scrapy/utils/log.py` replaces sys.stdout when LOG_STDOUT is true.

Users unfamiliar with the logging module and/or its usage in scrapy
or even external packages with no intent to be integrated (sometimes fairly)
in a framework that uses logging
may still dump output to stdout one way or another, eg calls to print().

My guess is that LOG_STDOUT is made to easily workaround such issues.
Even when you can inform your users, fixing external packages is often unfeasible.
You should generally have good practices, avoid playing directly with stdio (don't call print),
if you need to call a sub-process replace stdout/stderr with a stream logger etc,
but as I said this is not always feasible.

It's unfortunate that scrapy commands are called after scrapy's logging is initialized.

Even if scrapy used stderr for command output,
one could argue that capturing stderr is necessary because of some library's output.

Getting the spider list directly in scrapyd instead of scrapy is out of the question.
We would depend on too specific scrapy code that may change.
Also, I guess it'll be hard to do it without messing up sys.modules.

I think it's best to override LOG_STDOUT to false
in the command line scrapyd uses to get the spider list.
The only issue with this would be stdout usage during spider module initialization
eg a module dumping a warning to stdout when imported,
so, it doesn't break anything that is not already broken.

Anyone willing to fix (should be 1-2 lines really) and test this,
is welcome to open a pull request.
This is a scrapyd issue, not scrapyd-client,
the correct repository is https://github.com/scrapy/scrapyd

**Comment by jpmckinney** [comment]
> This is a scrapyd issue, not scrapyd-client,
> the correct repository is https://github.com/scrapy/scrapyd

Indeed: https://github.com/scrapy/scrapyd/pull/366
