### ISSUE TITLE
How to include the static file?

### ISSUE THREAD

**Issue by wspxh** [scrapy/scrapyd-client#46]
I can't find anyway to deploy my project with some .png files.

**Comment by Digenis** [comment]
See https://docs.python.org/distutils/setupscript.html#installing-package-data
Modify the setup.py generated by scrapyd-deploy to include your files.

You will also bump into this: https://github.com/scrapy/scrapyd-client#egg-caveats
> You should avoid using `__file__` in your project code as it doesn't play well with eggs. Consider using [pkgutil.get_data](http://docs.python.org/library/pkgutil.html#pkgutil.get_data) instead.

read up on `pkgutil.get_data`

**Comment by Digenis** [comment]
Leaving this issue open because I think it needs a sentence in the doc.

**Comment by wspxh** [comment]
Thank you.

**Comment by lalalalovewh** [comment]
I was very happy to find this problem because I had the same problem. I replaced '__file__' with 'pkgutil.get_data' but still don't know how to change the setup.py file.

The figure below is my static file location and my setup.py file:
![image](https://user-images.githubusercontent.com/49010160/56798310-1b36fa80-6849-11e9-9d94-b56f55e1a5fd.png)
![image](https://user-images.githubusercontent.com/49010160/56798445-51747a00-6849-11e9-94b1-c00b4f4983d0.png)

**Comment by Digenis** [comment]
You are repeating the 'packages' keyword argument to setup().
You probably meant to add this to the list returned by find_packages().
Are you sure that you need package_dir?
I think you can nest packages like this
and then package them as different packages.

I assume that find_packages() returns a package named ltpuller.
Try: `package_data={'ltpuller': 'tools/json/*.json'}`

**Comment by lalalalovewh** [comment]
Thank you for your help, I modified file to: package_data={'': ['tools/json/*.json']}, the crawler successfully packaged and run. Thanks again

**Comment by Digenis** [comment]
@lalalalovewh,
if that was helpful
consider adding an "examples" section in the readme
documenting how to include non-python files

**Comment by lalalalovewh** [comment]
@Digenis  
Ok, I will do this.

**Comment by jpmckinney** [comment]
Closed by #58
