### ISSUE TITLE
zsh: command not found: scrapyd-client 

### ISSUE THREAD

**Issue by yuseferi** [scrapy/scrapyd-client#51]
after I installed it via `pip3 install scrapyd-client` and got installed without any error  tried to run it but faced with  **zsh: command not found: scrapyd-client** it seems not found on zsh

**Comment by Digenis** [comment]
Hi @zhilevan,
The scrapyd-client cli is available in 1.2 which is still in alpha.
scrapyd-client 1.1 only provides the scrapyd-deploy command.

To install scrapyd-client-1.2, run `pip3 install scrapyd-client==1.2.0a1`
Please leave some feedback regarding the 1.2 version
so that we can improve it before releasing it.

**Comment by tkrugg** [comment]
Thanks, this helped. 
The client has been in alpha for more than 2 years now. Any reason it's not ready for stable yet?

**Comment by jpmckinney** [comment]
Duplicate #66 with respect to last question.
